name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Use Node.js 14.x for better compatibility with node-sass
        
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python2 g++ make
        
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies using Yarn
      run: yarn install
    
    - name: Build the project
      run: yarn run build

    - name: Copy build-dir files to root
      run: |
        sudo mv ./build/* ./
        sudo rm -r ./build
            
    - name: Deploy the project
      #working-directory: build  # Set to the directory where the build output is located
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add index.html main.js CNAME
        git commit -m "Deploy build output"
        git push origin HEAD:gh-pages --force

